site_name: "Visualizing Neural Networks: A Learning Journey"
theme:
  name: material
repo_name: 'codingfrank82/nn_viz'
repo_url: 'https://github.com/codingfrank82/nn_viz'
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
nav:
  - Homepage: index.md
  - Multilayer Perceptrons: MLP.ipynb