site_name: "Visualizing Neural Networks: A Learning Journey"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.footer
repo_name: 'codingfrank82/nn_viz'
repo_url: 'https://github.com/codingfrank82/nn_viz'
plugins:
  - tags
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
nav:
  - About: index.md
  - For Beginners:
    - Multilayer Perceptrons: beginers/MLP.ipynb
    - Convolutional Neural Networks: beginers/CNN.ipynb
  - Experiments:
    - Fourier Features: experiments/FourierFeatures.ipynb
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<codingfrank82@gmail.com>
    - icon: fontawesome/brands/github
      link: https://github.com/codingfrank82
